### ISSUE TITLE
浮窗每次初始化后第一次点击事件不生效

### ISSUE THREAD

**Issue by lingguanjie** [xuyingke/FloatWindowX#1]
浮窗每次初始化后第一次点击事件不生效，从第二次开始生效

**Comment by xuyingke** [comment]
确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。

**Comment by lingguanjie** [comment]
感谢解决！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月15日 16:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。

**Comment by xuyingke** [comment]
要感谢你提出来~    有需求也可以提出来。

**Comment by lingguanjie** [comment]
我在动画结束的方法中增加mClick=true;
该问题已解决（浮窗移动位置后，点击事件第一次还是会不生效），但我不确定别的地方有没有问题
| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月15日 16:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。

**Comment by xuyingke** [comment]
"我在动画结束的方法中增加mClick=true;"  这句不太理解。方便贴代码吗？










在 2022-08-16 14:53:28，"牧羊的星星" ***@***.***> 写道：

我在动画结束的方法中增加mClick=true;
该问题已解决（浮窗移动位置后，点击事件第一次还是会不生效），但我不确定别的地方有没有问题
| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月15日 16:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。

**Comment by lingguanjie** [comment]
我在FloatViewTouchListener类中onAnimationEnd的方法中增加mClick=true，该问题没有复现了 

| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月16日 18:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

"我在动画结束的方法中增加mClick=true;" 这句不太理解。方便贴代码吗？










在 2022-08-16 14:53:28，"牧羊的星星" ***@***.***> 写道：

我在动画结束的方法中增加mClick=true;
该问题已解决（浮窗移动位置后，点击事件第一次还是会不生效），但我不确定别的地方有没有问题
| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月15日 16:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。

**Comment by lingguanjie** [comment]
浮窗移动位置后，点击事件第一次还是会不生效，移动完成后打印的日志mClick:=false（FloatViewTouchListener类中）
| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月15日 16:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗每次初始化后第一次点击事件不生效 (Issue #1) |

确实存在这个问题。使用 1.0.2 aar 或者拉取最新代码即可修复。
