### ISSUE TITLE
浮窗随意移动位置后，还是会出现点击事件第一次不生效

### ISSUE THREAD

**Issue by lingguanjie** [xuyingke/FloatWindowX#3]
我在FloatViewTouchListener类中onAnimationEnd的方法中增加mClick=true，该问题没有复现了

**Comment by xuyingke** [comment]
你的目的是禁止点击事件吗？ 另外，不建议直接用源码~



在 2022-08-16 18:01:31，"牧羊的星星" ***@***.***> 写道：

我在FloatViewTouchListener类中onAnimationEnd的方法中增加mClick=true，该问题没有复现了

**Comment by lingguanjie** [comment]
我没想到禁用，我是发现随意移动位置后mClick=false；等于按钮被禁用了。在onAnimationEnd的方法中增加mClick=true；打开点击事件。


| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年8月16日 18:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xuyingke/FloatWindowX] 浮窗随意移动位置后，还是会出现点击事件第一次不生效 (Issue #3) |

你的目的是禁止点击事件吗？ 另外，不建议直接用源码~



在 2022-08-16 18:01:31，"牧羊的星星" ***@***.***> 写道：

我在FloatViewTouchListener类中onAnimationEnd的方法中增加mClick=true，该问题没有复现了
